"use client";

import '@/app/globals.scss'
import '@/styles/reset.scss'
import { DotGothic16 } from "@next/font/google";
import { RecoilRoot } from "recoil";
import Link from "next/link";
import { usePathname,useRouter } from 'next/navigation';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  const pathname = usePathname();
  return (
    
    <html lang="jp">
    <body>
      <header>
        <Link href="/" className="quit">{pathname === '/' ? '' : '戻る'}</Link>
      </header>
      <main>
      <RecoilRoot>{children}</RecoilRoot>
      </main>
      <footer></footer>
      </body>
    </html>
  )
}
