"use client";

import '@/app/globals.scss'
import '@/styles/reset.scss'
import { DotGothic16 } from "@next/font/google";
import { RecoilRoot } from "recoil";
import Link from "next/link";

const DotGothic16_normal = DotGothic16({
  weight: "400",
  subsets: ["cyrillic"],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
    <body className={DotGothic16_normal.className}>
      <header>
        <Link href="/" className="quit">もどる</Link>
      </header>
      <main>
      <RecoilRoot>{children}</RecoilRoot>
      </main>
      <footer></footer>
      </body>
    </html>
  )
}
